server:
  servlet:
    context-path: /exchange_rate

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
      format_sql: true

batch:
  openapi: https://openapi.taifex.com.tw/v1/DailyForeignExchangeRates